version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '${SERVER_PORT}:80'
    links:
      - php
    depends_on:
      - php
      - mysql
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: php
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0.0
    container_name: mysql
    restart: always
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT}
    networks:
      - backend

networks:
  www:
    external: true
  backend:
    ipam:
      driver: default
